/**
 * Enterprise Workflow Templates — DP Media OS
 *
 * Defines complete production pipelines for all three project types.
 * Every project created from these templates gets a fully operational
 * workspace: stages, objectives, timelines, dependencies, and assignments.
 */

export interface EnterpriseObjectiveTemplate {
  title: string;
  description: string;
  department: string;
  priority: 'High' | 'Medium' | 'Low';
  estimated_hours: number;
  offset_ratio: number; // 0–1, position within stage timeline
  checklist: { task: string; done: boolean }[];
  depends_on: string[]; // Titles of blocking objectives
  is_client_visible: boolean;
  is_ai_task: boolean;
}

export interface EnterpriseStageTemplate {
  name: string;
  order: number;
  weight: number; // Proportion of total timeline (all weights should sum to 1)
  objectives: EnterpriseObjectiveTemplate[];
}

export interface EnterpriseProjectTemplate {
  project_type: string;
  default_days: number; // Used when no deadline is set
  stages: EnterpriseStageTemplate[];
}

// ============================================================
// 1. AI PRODUCTION PIPELINE
// ============================================================
export const AIProductionTemplate: EnterpriseProjectTemplate = {
  project_type: 'AI Production',
  default_days: 45,
  stages: [
    {
      name: 'Research & Strategy',
      order: 1,
      weight: 0.10,
      objectives: [
        {
          title: 'Brand Research',
          description: 'Deep dive into the client brand — values, voice, visual identity, market positioning, and competitor landscape.',
          department: 'Creative',
          priority: 'High',
          estimated_hours: 6,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Gather existing brand assets', done: false },
            { task: 'Document brand voice and tone', done: false },
            { task: 'Identify key visual language', done: false },
            { task: 'Review past campaigns', done: false },
          ],
          depends_on: [],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Competitor Analysis',
          description: 'Analyze competing brands\' AI-generated content, visual styles, and differentiation opportunities.',
          department: 'Creative',
          priority: 'Medium',
          estimated_hours: 4,
          offset_ratio: 0.3,
          checklist: [
            { task: 'Identify 5 direct competitors', done: false },
            { task: 'Document visual style of each', done: false },
            { task: 'Identify whitespace opportunities', done: false },
          ],
          depends_on: ['Brand Research'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Moodboard Creation',
          description: 'Curate visual references, style direction, color palette, and aesthetic touchstones for the AI generation pipeline.',
          department: 'Creative',
          priority: 'High',
          estimated_hours: 5,
          offset_ratio: 0.5,
          checklist: [
            { task: 'Collect 20+ visual references', done: false },
            { task: 'Define color story', done: false },
            { task: 'Define lighting direction', done: false },
            { task: 'Define texture and surface language', done: false },
          ],
          depends_on: ['Brand Research'],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Visual Direction Approval',
          description: 'Present moodboard and creative direction to client. Obtain written approval before AI generation begins.',
          department: 'Creative',
          priority: 'High',
          estimated_hours: 2,
          offset_ratio: 0.8,
          checklist: [
            { task: 'Present moodboard to client', done: false },
            { task: 'Document approval in writing', done: false },
            { task: 'Lock visual direction', done: false },
          ],
          depends_on: ['Moodboard Creation'],
          is_client_visible: true,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Prompt Engineering',
      order: 2,
      weight: 0.15,
      objectives: [
        {
          title: 'Master Prompt Design',
          description: 'Engineer the core prompt system that drives the entire visual pipeline. Establish style tokens, quality suffixes, and base instruction sets.',
          department: 'AI',
          priority: 'High',
          estimated_hours: 8,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Define base style tokens', done: false },
            { task: 'Build quality enhancement suffix stack', done: false },
            { task: 'Test with 5 seed generations', done: false },
            { task: 'Document master prompt blueprint', done: false },
          ],
          depends_on: ['Visual Direction Approval'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Character Consistency Prompt',
          description: 'Design prompts that maintain character identity, facial features, and style consistency across multiple generation passes.',
          department: 'AI',
          priority: 'High',
          estimated_hours: 6,
          offset_ratio: 0.25,
          checklist: [
            { task: 'Define character LoRA or IP-Adapter seed', done: false },
            { task: 'Test multi-angle consistency', done: false },
            { task: 'Verify expression range', done: false },
          ],
          depends_on: ['Master Prompt Design'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Environment Prompt',
          description: 'Engineer background, environment, and location prompts that integrate seamlessly with character generation.',
          department: 'AI',
          priority: 'Medium',
          estimated_hours: 4,
          offset_ratio: 0.5,
          checklist: [
            { task: 'Define environment style tokens', done: false },
            { task: 'Test character-background integration', done: false },
            { task: 'Verify lighting consistency', done: false },
          ],
          depends_on: ['Master Prompt Design'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Camera Motion Prompt',
          description: 'Define camera movement descriptors for video generation (dolly, zoom, pan, orbit) integrated into prompt structure.',
          department: 'AI',
          priority: 'Medium',
          estimated_hours: 3,
          offset_ratio: 0.65,
          checklist: [
            { task: 'Map motion keywords to providers', done: false },
            { task: 'Test motion consistency', done: false },
          ],
          depends_on: ['Master Prompt Design'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Negative Prompt Optimization',
          description: 'Build and validate the negative prompt system to eliminate artifacts, anatomical errors, and style inconsistencies.',
          department: 'AI',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.8,
          checklist: [
            { task: 'Build base negative prompt stack', done: false },
            { task: 'Test artifact elimination', done: false },
            { task: 'Document finalized negative prompt', done: false },
          ],
          depends_on: ['Character Consistency Prompt', 'Environment Prompt'],
          is_client_visible: false,
          is_ai_task: true,
        },
      ],
    },
    {
      name: 'AI Asset Generation',
      order: 3,
      weight: 0.20,
      objectives: [
        {
          title: 'Character Generation',
          description: 'Generate all primary character frames using the approved prompt system. Produce high-resolution base assets.',
          department: 'AI',
          priority: 'High',
          estimated_hours: 12,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Generate 50+ character variants', done: false },
            { task: 'QC for anatomical accuracy', done: false },
            { task: 'Select hero frames', done: false },
          ],
          depends_on: ['Negative Prompt Optimization'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Background Generation',
          description: 'Generate all environment and background assets. Ensure visual coherence with character assets.',
          department: 'AI',
          priority: 'High',
          estimated_hours: 8,
          offset_ratio: 0.2,
          checklist: [
            { task: 'Generate environment frames', done: false },
            { task: 'Match lighting with character assets', done: false },
            { task: 'Select final backgrounds', done: false },
          ],
          depends_on: ['Negative Prompt Optimization'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Product Visualization',
          description: 'Generate product-specific visual assets — packaging, product shots, lifestyle integration.',
          department: 'AI',
          priority: 'Medium',
          estimated_hours: 8,
          offset_ratio: 0.4,
          checklist: [
            { task: 'Generate product hero shots', done: false },
            { task: 'Generate lifestyle context shots', done: false },
            { task: 'Verify brand accuracy', done: false },
          ],
          depends_on: ['Character Generation', 'Background Generation'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Image Upscaling',
          description: 'Upscale all selected frames to 4K using AI upscaling pipeline (Topaz, Magnific, or equivalent).',
          department: 'AI',
          priority: 'Medium',
          estimated_hours: 6,
          offset_ratio: 0.65,
          checklist: [
            { task: 'Run upscaling pass on hero frames', done: false },
            { task: 'QC for upscaling artifacts', done: false },
            { task: 'Export final resolution assets', done: false },
          ],
          depends_on: ['Product Visualization'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Consistency Verification',
          description: 'Full QA pass to verify that all generated assets are visually consistent with each other and the approved direction.',
          department: 'AI',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.85,
          checklist: [
            { task: 'Side-by-side consistency check', done: false },
            { task: 'Verify color temperature alignment', done: false },
            { task: 'Flag and regenerate inconsistent frames', done: false },
          ],
          depends_on: ['Image Upscaling'],
          is_client_visible: false,
          is_ai_task: true,
        },
      ],
    },
    {
      name: 'AI Video Processing',
      order: 4,
      weight: 0.15,
      objectives: [
        {
          title: 'Image-to-Video Conversion',
          description: 'Convert approved image assets to video using AI video generation models (Runway, Kling, Sora, etc.).',
          department: 'AI',
          priority: 'High',
          estimated_hours: 16,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Queue all hero frames for I2V generation', done: false },
            { task: 'Define motion intent per frame', done: false },
            { task: 'Generate and select best motion variants', done: false },
          ],
          depends_on: ['Consistency Verification'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Motion Interpolation',
          description: 'Smooth frame rates from generation output (typically 12–16fps) up to 24 or 30fps for broadcast.',
          department: 'AI',
          priority: 'Medium',
          estimated_hours: 6,
          offset_ratio: 0.4,
          checklist: [
            { task: 'Apply FILM / RIFE interpolation', done: false },
            { task: 'Review for ghosting artifacts', done: false },
          ],
          depends_on: ['Image-to-Video Conversion'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Lip Sync Generation',
          description: 'If voiceover required, apply AI lip sync to character videos (SadTalker, LatentSync, etc.).',
          department: 'AI',
          priority: 'Medium',
          estimated_hours: 6,
          offset_ratio: 0.55,
          checklist: [
            { task: 'Sync voiceover audio to character', done: false },
            { task: 'QC for lip sync accuracy', done: false },
            { task: 'Correct mismatched frames', done: false },
          ],
          depends_on: ['Motion Interpolation'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Frame Stabilization',
          description: 'Apply temporal stabilization to remove jitter and camera shake from generated video sequences.',
          department: 'AI',
          priority: 'Medium',
          estimated_hours: 4,
          offset_ratio: 0.8,
          checklist: [
            { task: 'Run stabilization pipeline', done: false },
            { task: 'Review motion artifacts', done: false },
          ],
          depends_on: ['Motion Interpolation'],
          is_client_visible: false,
          is_ai_task: true,
        },
      ],
    },
    {
      name: 'AI Enhancement',
      order: 5,
      weight: 0.12,
      objectives: [
        {
          title: 'Color Grading',
          description: 'Apply professional color grading using DaVinci Resolve or equivalent. Match brand palette and cinematic style.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 8,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Apply base grade', done: false },
            { task: 'Match skin tones across cuts', done: false },
            { task: 'Apply creative LUT', done: false },
            { task: 'Export graded master', done: false },
          ],
          depends_on: ['Frame Stabilization'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'AI Cleanup',
          description: 'Use AI tools to remove visible generation artifacts, pixel noise, and temporal inconsistencies.',
          department: 'AI',
          priority: 'High',
          estimated_hours: 6,
          offset_ratio: 0.3,
          checklist: [
            { task: 'Run AI denoising pass', done: false },
            { task: 'Remove pixel artifacts', done: false },
          ],
          depends_on: ['Color Grading'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Artifact Removal',
          description: 'Manual frame-by-frame cleanup of persistent AI generation artifacts that automated passes missed.',
          department: 'Post-Production',
          priority: 'Medium',
          estimated_hours: 8,
          offset_ratio: 0.55,
          checklist: [
            { task: 'Review all frames for artifacts', done: false },
            { task: 'Manually paint/fix problem frames', done: false },
          ],
          depends_on: ['AI Cleanup'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'VFX Enhancement',
          description: 'Add supplemental VFX elements — particle systems, lens flares, environment effects — to enrich the AI-generated footage.',
          department: 'Post-Production',
          priority: 'Medium',
          estimated_hours: 10,
          offset_ratio: 0.75,
          checklist: [
            { task: 'Design VFX elements', done: false },
            { task: 'Composite VFX into footage', done: false },
            { task: 'QC VFX integration', done: false },
          ],
          depends_on: ['Artifact Removal'],
          is_client_visible: false,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Sound & Voice',
      order: 6,
      weight: 0.08,
      objectives: [
        {
          title: 'AI Voiceover',
          description: 'Generate AI voiceover using ElevenLabs or equivalent. Match brand voice profile and tonal requirements.',
          department: 'Audio',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Select voice model', done: false },
            { task: 'Generate voiceover takes', done: false },
            { task: 'Clean and EQ audio', done: false },
          ],
          depends_on: ['Visual Direction Approval'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'Sound Design',
          description: 'Create foley, ambient sound, and SFX layer that complements the visual narrative.',
          department: 'Audio',
          priority: 'Medium',
          estimated_hours: 6,
          offset_ratio: 0.3,
          checklist: [
            { task: 'Identify key sound design moments', done: false },
            { task: 'Source and record SFX', done: false },
            { task: 'Layer into timeline', done: false },
          ],
          depends_on: ['AI Voiceover'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Music Integration',
          description: 'License or compose background music. Sync to video pacing and emotional beats.',
          department: 'Audio',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.55,
          checklist: [
            { task: 'Select or compose music track', done: false },
            { task: 'Sync music to edit', done: false },
            { task: 'Confirm licensing clearance', done: false },
          ],
          depends_on: ['Sound Design'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Audio Cleanup',
          description: 'Final audio mix — levels, compression, EQ, loudness normalization (LUFS-R compliance for broadcast).',
          department: 'Audio',
          priority: 'High',
          estimated_hours: 3,
          offset_ratio: 0.8,
          checklist: [
            { task: 'Mix all audio tracks', done: false },
            { task: 'Normalize to -14 LUFS for streaming', done: false },
            { task: 'Export audio master', done: false },
          ],
          depends_on: ['Music Integration'],
          is_client_visible: false,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Review & QA',
      order: 7,
      weight: 0.10,
      objectives: [
        {
          title: 'Internal Review',
          description: 'Internal team QA pass before client-facing review. Validate technical quality, brand alignment, and delivery readiness.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 3,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Technical QC (resolution, codec, frame rate)', done: false },
            { task: 'Brand compliance check', done: false },
            { task: 'Audio sync verification', done: false },
          ],
          depends_on: ['VFX Enhancement', 'Audio Cleanup'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Client Review',
          description: 'Deliver cut to client for feedback. Collect structured revision notes via client portal.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 2,
          offset_ratio: 0.3,
          checklist: [
            { task: 'Upload to client delivery portal', done: false },
            { task: 'Brief client on review process', done: false },
            { task: 'Collect timecoded feedback', done: false },
          ],
          depends_on: ['Internal Review'],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Revision Round',
          description: 'Execute approved revisions based on client feedback. Track revision count against contractual limit.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 6,
          offset_ratio: 0.55,
          checklist: [
            { task: 'Log all revision requests', done: false },
            { task: 'Execute revisions', done: false },
            { task: 'Internal QC after revisions', done: false },
          ],
          depends_on: ['Client Review'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Final Approval',
          description: 'Obtain formal written client approval on final cut before master export.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 1,
          offset_ratio: 0.85,
          checklist: [
            { task: 'Send final cut to client', done: false },
            { task: 'Receive written approval confirmation', done: false },
          ],
          depends_on: ['Revision Round'],
          is_client_visible: true,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Delivery',
      order: 8,
      weight: 0.10,
      objectives: [
        {
          title: 'Master Export',
          description: 'Export broadcast-quality master file at full resolution with all deliverable specifications.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 2,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Export ProRes/DNxHD master', done: false },
            { task: 'Export H.264 web version', done: false },
            { task: 'Verify file integrity', done: false },
          ],
          depends_on: ['Final Approval'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Social Export Variants',
          description: 'Create platform-optimized variants for Instagram, YouTube, LinkedIn, and other required channels.',
          department: 'Post-Production',
          priority: 'Medium',
          estimated_hours: 3,
          offset_ratio: 0.3,
          checklist: [
            { task: 'Export 9:16 vertical variant', done: false },
            { task: 'Export 1:1 square variant', done: false },
            { task: 'Export 16:9 widescreen variant', done: false },
          ],
          depends_on: ['Master Export'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Cloud Backup',
          description: 'Back up all project files, raw assets, and final exports to cloud storage with organized folder structure.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 2,
          offset_ratio: 0.6,
          checklist: [
            { task: 'Upload to cloud storage', done: false },
            { task: 'Verify backup integrity', done: false },
            { task: 'Document file structure', done: false },
          ],
          depends_on: ['Master Export'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Delivery Upload',
          description: 'Upload final deliverables to client portal and confirm receipt.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 1,
          offset_ratio: 0.85,
          checklist: [
            { task: 'Upload to client delivery link', done: false },
            { task: 'Send delivery confirmation email', done: false },
            { task: 'Confirm client download', done: false },
          ],
          depends_on: ['Social Export Variants', 'Cloud Backup'],
          is_client_visible: true,
          is_ai_task: false,
        },
      ],
    },
  ],
};

// ============================================================
// 2. HYBRID PRODUCTION PIPELINE
// ============================================================
export const HybridProductionTemplate: EnterpriseProjectTemplate = {
  project_type: 'Hybrid Production',
  default_days: 35,
  stages: [
    {
      name: 'Pre-Production',
      order: 1,
      weight: 0.20,
      objectives: [
        {
          title: 'Script Writing',
          description: 'Write and finalize the production script, including dialogue, action lines, and visual direction notes.',
          department: 'Creative',
          priority: 'High',
          estimated_hours: 8,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Draft script v1', done: false },
            { task: 'Internal script review', done: false },
            { task: 'Client script approval', done: false },
          ],
          depends_on: [],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Storyboarding',
          description: 'Translate approved script into visual storyboards, defining each shot, angle, and composition.',
          department: 'Creative',
          priority: 'High',
          estimated_hours: 10,
          offset_ratio: 0.25,
          checklist: [
            { task: 'Rough storyboard all scenes', done: false },
            { task: 'Add camera direction notes', done: false },
            { task: 'Client storyboard approval', done: false },
          ],
          depends_on: ['Script Writing'],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Shot Division',
          description: 'Break down the approved storyboard into a detailed shot list with camera specs, lens choices, and technical requirements.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.4,
          checklist: [
            { task: 'Create shot list spreadsheet', done: false },
            { task: 'Define lens and camera specs per shot', done: false },
          ],
          depends_on: ['Storyboarding'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Talent Finalization',
          description: 'Cast, contract, and confirm all on-screen talent. Coordinate wardrobe, makeup, and scheduling.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 6,
          offset_ratio: 0.4,
          checklist: [
            { task: 'Finalize talent selection', done: false },
            { task: 'Sign talent contracts', done: false },
            { task: 'Schedule wardrobe/makeup call', done: false },
          ],
          depends_on: ['Script Writing'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Costume Planning',
          description: 'Source and confirm all wardrobe for talent. Ensure brand alignment and visual consistency with moodboard.',
          department: 'Production',
          priority: 'Medium',
          estimated_hours: 4,
          offset_ratio: 0.5,
          checklist: [
            { task: 'Source costume pieces', done: false },
            { task: 'Fitting session with talent', done: false },
            { task: 'Lock final costumes', done: false },
          ],
          depends_on: ['Talent Finalization'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Equipment Planning',
          description: 'Specify and book all camera, lighting, audio, and grip equipment for the production shoot days.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 3,
          offset_ratio: 0.55,
          checklist: [
            { task: 'Generate equipment list from shot list', done: false },
            { task: 'Book camera package', done: false },
            { task: 'Book lighting and grip', done: false },
          ],
          depends_on: ['Shot Division'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Location Approval',
          description: 'Scout, photograph, and secure all filming locations. Obtain required permits.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 6,
          offset_ratio: 0.6,
          checklist: [
            { task: 'Scout and document locations', done: false },
            { task: 'Client location approval', done: false },
            { task: 'Obtain filming permits', done: false },
          ],
          depends_on: ['Shot Division'],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Production Schedule',
          description: 'Create comprehensive call sheets, shoot schedules, and logistical plans for all production days.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.8,
          checklist: [
            { task: 'Draft day-by-day shoot schedule', done: false },
            { task: 'Create call sheets', done: false },
            { task: 'Share schedule with all crew', done: false },
          ],
          depends_on: ['Equipment Planning', 'Location Approval', 'Talent Finalization'],
          is_client_visible: false,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Production',
      order: 2,
      weight: 0.20,
      objectives: [
        {
          title: 'Camera Setup',
          description: 'Set up and calibrate all camera systems, lenses, and monitoring on location.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 3,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Build camera rig', done: false },
            { task: 'Set recording parameters', done: false },
            { task: 'Calibrate monitoring', done: false },
          ],
          depends_on: ['Production Schedule'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Lighting Setup',
          description: 'Design and execute the lighting plan for each location and scene. Match approved moodboard aesthetics.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.1,
          checklist: [
            { task: 'Set up lighting grid', done: false },
            { task: 'Balance for camera exposure', done: false },
            { task: 'Test on talent', done: false },
          ],
          depends_on: ['Camera Setup'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Principal Photography',
          description: 'Execute the main shoot day(s). Capture all primary footage per approved shot list.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 24,
          offset_ratio: 0.2,
          checklist: [
            { task: 'Complete all shots in shot list', done: false },
            { task: 'Director approval on each scene', done: false },
            { task: 'Collect safety backups for key shots', done: false },
          ],
          depends_on: ['Lighting Setup'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Backup Footage',
          description: 'Capture supplemental B-roll, cutaways, and alternate takes to support editing flexibility.',
          department: 'Production',
          priority: 'Medium',
          estimated_hours: 6,
          offset_ratio: 0.6,
          checklist: [
            { task: 'Shoot B-roll for all primary scenes', done: false },
            { task: 'Capture alternate angles', done: false },
          ],
          depends_on: ['Principal Photography'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'DIT Management',
          description: 'Manage data ingest, on-set backup, and dailies distribution. Protect all captured media.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.8,
          checklist: [
            { task: 'Ingest all cards to primary drive', done: false },
            { task: 'Create backup copy', done: false },
            { task: 'Verify checksums', done: false },
            { task: 'Deliver dailies', done: false },
          ],
          depends_on: ['Principal Photography'],
          is_client_visible: false,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'AI Processing',
      order: 3,
      weight: 0.15,
      objectives: [
        {
          title: 'AI Cleanup',
          description: 'Use AI tools to clean footage — remove wires, blemishes, unwanted objects, and production equipment.',
          department: 'AI',
          priority: 'High',
          estimated_hours: 8,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Identify all cleanup shots', done: false },
            { task: 'Run AI cleanup pipeline', done: false },
            { task: 'QC all cleaned frames', done: false },
          ],
          depends_on: ['DIT Management'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'AI Object Removal',
          description: 'Remove specific on-set objects (cables, crew reflections, logos) using AI inpainting.',
          department: 'AI',
          priority: 'Medium',
          estimated_hours: 6,
          offset_ratio: 0.3,
          checklist: [
            { task: 'Flag all object removal shots', done: false },
            { task: 'Run AI inpainting', done: false },
            { task: 'Manual touch-up where AI fails', done: false },
          ],
          depends_on: ['AI Cleanup'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'AI Enhancement',
          description: 'Enhance footage quality — AI upscaling, denoising, detail enhancement, and sharpening passes.',
          department: 'AI',
          priority: 'Medium',
          estimated_hours: 6,
          offset_ratio: 0.5,
          checklist: [
            { task: 'Run AI upscaling if needed', done: false },
            { task: 'Apply AI denoising', done: false },
          ],
          depends_on: ['AI Object Removal'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'AI Background Generation',
          description: 'Replace or extend backgrounds using AI generation where practical backgrounds are unusable.',
          department: 'AI',
          priority: 'Medium',
          estimated_hours: 8,
          offset_ratio: 0.65,
          checklist: [
            { task: 'Identify background replacement shots', done: false },
            { task: 'Generate replacement backgrounds', done: false },
            { task: 'Composite backgrounds into footage', done: false },
          ],
          depends_on: ['AI Enhancement'],
          is_client_visible: false,
          is_ai_task: true,
        },
        {
          title: 'AI Motion Extension',
          description: 'Extend short takes or fill missing frames using AI video generation and frame interpolation.',
          department: 'AI',
          priority: 'Low',
          estimated_hours: 4,
          offset_ratio: 0.85,
          checklist: [
            { task: 'Identify shots needing extension', done: false },
            { task: 'Generate extension frames', done: false },
            { task: 'Blend with original footage', done: false },
          ],
          depends_on: ['AI Background Generation'],
          is_client_visible: false,
          is_ai_task: true,
        },
      ],
    },
    {
      name: 'Post-Production',
      order: 4,
      weight: 0.20,
      objectives: [
        {
          title: 'Video Editing',
          description: 'Assemble all footage into a coherent cut following the approved script and storyboard structure.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 20,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Sync and organize all footage', done: false },
            { task: 'Assemble rough cut', done: false },
            { task: 'Refine to picture lock', done: false },
          ],
          depends_on: ['AI Motion Extension'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Sound Design',
          description: 'Create complete sound design: foley, ambience, and SFX to enhance the visual edit.',
          department: 'Audio',
          priority: 'Medium',
          estimated_hours: 8,
          offset_ratio: 0.4,
          checklist: [
            { task: 'Create foley track', done: false },
            { task: 'Build ambience layer', done: false },
            { task: 'Design SFX moments', done: false },
          ],
          depends_on: ['Video Editing'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Music Sync',
          description: 'License, compose, or adapt background music. Sync to video pacing and emotional beats.',
          department: 'Audio',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.5,
          checklist: [
            { task: 'Select music', done: false },
            { task: 'Sync to picture', done: false },
            { task: 'Confirm licensing', done: false },
          ],
          depends_on: ['Sound Design'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Color Grading',
          description: 'Grade all footage to final look. Match visual consistency across footage and AI-generated assets.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 10,
          offset_ratio: 0.6,
          checklist: [
            { task: 'Primary correction pass', done: false },
            { task: 'Secondary and creative grade', done: false },
            { task: 'Match AI assets to shot footage', done: false },
          ],
          depends_on: ['Video Editing'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Subtitle Creation',
          description: 'Create and style subtitles or lower thirds for accessibility and social media delivery.',
          department: 'Post-Production',
          priority: 'Low',
          estimated_hours: 3,
          offset_ratio: 0.8,
          checklist: [
            { task: 'Transcribe dialogue', done: false },
            { task: 'Style and position subtitles', done: false },
            { task: 'Export subtitle file (SRT)', done: false },
          ],
          depends_on: ['Video Editing'],
          is_client_visible: false,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Review',
      order: 5,
      weight: 0.10,
      objectives: [
        {
          title: 'Internal QC',
          description: 'Full internal quality control pass before client presentation. Technical and creative review.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 3,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Technical spec check', done: false },
            { task: 'Creative alignment check', done: false },
            { task: 'Audio sync verification', done: false },
          ],
          depends_on: ['Color Grading', 'Music Sync', 'Subtitle Creation'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Client Feedback',
          description: 'Present edit to client and collect structured, timecoded feedback.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 2,
          offset_ratio: 0.3,
          checklist: [
            { task: 'Upload to client portal', done: false },
            { task: 'Present in review session', done: false },
            { task: 'Document all feedback', done: false },
          ],
          depends_on: ['Internal QC'],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Revision Management',
          description: 'Execute all approved revisions from client feedback within contractual revision limits.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 8,
          offset_ratio: 0.55,
          checklist: [
            { task: 'Log revision requests', done: false },
            { task: 'Execute revisions', done: false },
            { task: 'Re-QC after revisions', done: false },
          ],
          depends_on: ['Client Feedback'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Approval Signoff',
          description: 'Obtain formal written approval from client on final version before delivery.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 1,
          offset_ratio: 0.85,
          checklist: [
            { task: 'Send final version for approval', done: false },
            { task: 'Receive written sign-off', done: false },
          ],
          depends_on: ['Revision Management'],
          is_client_visible: true,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Delivery',
      order: 6,
      weight: 0.15,
      objectives: [
        {
          title: 'Final Export',
          description: 'Export all final deliverable files in all required formats and resolutions.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 3,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Export broadcast master', done: false },
            { task: 'Export web versions', done: false },
            { task: 'Verify all exports', done: false },
          ],
          depends_on: ['Approval Signoff'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Archive Project',
          description: 'Organize and archive all project files, raw footage, and project files for long-term storage.',
          department: 'Production',
          priority: 'Medium',
          estimated_hours: 2,
          offset_ratio: 0.35,
          checklist: [
            { task: 'Organize folder structure', done: false },
            { task: 'Upload raw footage to archive', done: false },
            { task: 'Upload project files to archive', done: false },
          ],
          depends_on: ['Final Export'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Delivery Upload',
          description: 'Deliver all final files to client via portal or cloud delivery link.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 1,
          offset_ratio: 0.6,
          checklist: [
            { task: 'Upload finals to delivery portal', done: false },
            { task: 'Send delivery confirmation', done: false },
            { task: 'Confirm client receipt', done: false },
          ],
          depends_on: ['Final Export'],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Social Media Adaptations',
          description: 'Create platform-specific adaptations optimized for each required social media channel.',
          department: 'Post-Production',
          priority: 'Medium',
          estimated_hours: 4,
          offset_ratio: 0.75,
          checklist: [
            { task: 'Export 9:16 reel variant', done: false },
            { task: 'Export 1:1 square variant', done: false },
            { task: 'Add platform-specific captions', done: false },
          ],
          depends_on: ['Final Export'],
          is_client_visible: false,
          is_ai_task: false,
        },
      ],
    },
  ],
};

// ============================================================
// 3. NORMAL PRODUCTION PIPELINE
// ============================================================
export const NormalProductionTemplate: EnterpriseProjectTemplate = {
  project_type: 'Normal Production',
  default_days: 25,
  stages: [
    {
      name: 'Planning',
      order: 1,
      weight: 0.20,
      objectives: [
        {
          title: 'Script Finalization',
          description: 'Write and lock the production script. Obtain client approval before any production begins.',
          department: 'Creative',
          priority: 'High',
          estimated_hours: 8,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Draft script v1', done: false },
            { task: 'Director review', done: false },
            { task: 'Client script approval', done: false },
          ],
          depends_on: [],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Storyboard',
          description: 'Translate script into visual storyboards that define shot composition, angles, and sequence.',
          department: 'Creative',
          priority: 'High',
          estimated_hours: 8,
          offset_ratio: 0.25,
          checklist: [
            { task: 'Sketch storyboard frames', done: false },
            { task: 'Add direction notes', done: false },
            { task: 'Client storyboard approval', done: false },
          ],
          depends_on: ['Script Finalization'],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Crew Assignment',
          description: 'Assign all crew roles — DoP, camera, gaffer, sound, makeup — and confirm availability.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 3,
          offset_ratio: 0.3,
          checklist: [
            { task: 'Confirm DoP', done: false },
            { task: 'Confirm camera crew', done: false },
            { task: 'Confirm sound team', done: false },
            { task: 'Confirm makeup/styling', done: false },
          ],
          depends_on: ['Script Finalization'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Location Planning',
          description: 'Scout and confirm all shooting locations. Secure necessary permits and access arrangements.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 6,
          offset_ratio: 0.45,
          checklist: [
            { task: 'Scout locations', done: false },
            { task: 'Photograph and document', done: false },
            { task: 'Secure permits', done: false },
            { task: 'Client location approval', done: false },
          ],
          depends_on: ['Storyboard'],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Equipment Allocation',
          description: 'Specify and book all production equipment — camera, lenses, lighting, audio, and grip.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 3,
          offset_ratio: 0.55,
          checklist: [
            { task: 'Generate equipment list', done: false },
            { task: 'Book and confirm equipment', done: false },
          ],
          depends_on: ['Storyboard'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Shoot Schedule',
          description: 'Create final call sheets, shooting schedule, and logistics plan for all production days.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.75,
          checklist: [
            { task: 'Create detailed call sheets', done: false },
            { task: 'Build hour-by-hour schedule', done: false },
            { task: 'Share with full crew', done: false },
          ],
          depends_on: ['Crew Assignment', 'Location Planning', 'Equipment Allocation'],
          is_client_visible: false,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Production',
      order: 2,
      weight: 0.25,
      objectives: [
        {
          title: 'Shoot Day Setup',
          description: 'Set up all production equipment on location. Conduct camera and audio tests before talent arrival.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Set up camera and lenses', done: false },
            { task: 'Build and test lighting', done: false },
            { task: 'Set up audio', done: false },
            { task: 'Run camera tests', done: false },
          ],
          depends_on: ['Shoot Schedule'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Camera Operations',
          description: 'Execute all camera operation requirements for the shoot — handheld, dolly, gimbal, or locked-off shots.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 16,
          offset_ratio: 0.2,
          checklist: [
            { task: 'Execute shot list', done: false },
            { task: 'Director review of each scene', done: false },
            { task: 'Coverage for all key moments', done: false },
          ],
          depends_on: ['Shoot Day Setup'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Lighting Operations',
          description: 'Manage and adapt lighting throughout the shoot day for each scene and setup.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 8,
          offset_ratio: 0.2,
          checklist: [
            { task: 'Adapt lighting per scene', done: false },
            { task: 'Manage daylight continuity', done: false },
          ],
          depends_on: ['Shoot Day Setup'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Audio Recording',
          description: 'Record all production audio — dialogue, ambience, and wild sound — at broadcast quality.',
          department: 'Audio',
          priority: 'High',
          estimated_hours: 8,
          offset_ratio: 0.2,
          checklist: [
            { task: 'Record all dialogue tracks', done: false },
            { task: 'Capture room ambience', done: false },
            { task: 'Record wild sound for edit', done: false },
          ],
          depends_on: ['Shoot Day Setup'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Backup Management',
          description: 'Manage on-set data backup, card management, and media security throughout production.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 3,
          offset_ratio: 0.75,
          checklist: [
            { task: 'Ingest all cards', done: false },
            { task: 'Create dual backup', done: false },
            { task: 'Verify checksums', done: false },
          ],
          depends_on: ['Camera Operations'],
          is_client_visible: false,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Editing',
      order: 3,
      weight: 0.25,
      objectives: [
        {
          title: 'Footage Sorting',
          description: 'Organize, log, and rate all footage. Create bins and selects for efficient editing.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 4,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Sync all footage to project', done: false },
            { task: 'Log and rate clips', done: false },
            { task: 'Organize into scene bins', done: false },
          ],
          depends_on: ['Backup Management'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Rough Cut',
          description: 'Assemble first rough cut from selects. Focus on structure, pacing, and story. Share internally for review.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 12,
          offset_ratio: 0.2,
          checklist: [
            { task: 'Assemble rough cut', done: false },
            { task: 'Add temp music and sound', done: false },
            { task: 'Internal rough cut review', done: false },
          ],
          depends_on: ['Footage Sorting'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Final Edit',
          description: 'Refine rough cut to picture lock. All editorial decisions finalized at this stage.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 10,
          offset_ratio: 0.45,
          checklist: [
            { task: 'Tighten all edits', done: false },
            { task: 'Add titles and graphics', done: false },
            { task: 'Picture lock', done: false },
          ],
          depends_on: ['Rough Cut'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Audio Mix',
          description: 'Complete audio post-production: dialogue editing, music sync, SFX, and final mix.',
          department: 'Audio',
          priority: 'High',
          estimated_hours: 6,
          offset_ratio: 0.65,
          checklist: [
            { task: 'Clean and sync dialogue', done: false },
            { task: 'Layer music and SFX', done: false },
            { task: 'Final mix and normalize', done: false },
          ],
          depends_on: ['Final Edit'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Color Grade',
          description: 'Apply professional color grade to achieve the final visual look.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 6,
          offset_ratio: 0.8,
          checklist: [
            { task: 'Primary correction', done: false },
            { task: 'Creative grade / LUT application', done: false },
            { task: 'Export graded master', done: false },
          ],
          depends_on: ['Final Edit'],
          is_client_visible: false,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Review',
      order: 4,
      weight: 0.15,
      objectives: [
        {
          title: 'Internal Approval',
          description: 'Internal creative and technical review before client presentation.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 2,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Creative review', done: false },
            { task: 'Technical QC', done: false },
          ],
          depends_on: ['Color Grade', 'Audio Mix'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Client Review',
          description: 'Present final cut to client via portal. Collect structured feedback.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 2,
          offset_ratio: 0.3,
          checklist: [
            { task: 'Upload to client portal', done: false },
            { task: 'Present and collect feedback', done: false },
          ],
          depends_on: ['Internal Approval'],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Revisions',
          description: 'Execute all approved client revisions within contractual scope.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 6,
          offset_ratio: 0.55,
          checklist: [
            { task: 'Log revision notes', done: false },
            { task: 'Execute revisions', done: false },
            { task: 'QC after revisions', done: false },
          ],
          depends_on: ['Client Review'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Final QA',
          description: 'Final quality assurance pass on revised cut before delivery export.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 1,
          offset_ratio: 0.8,
          checklist: [
            { task: 'Full playback QC', done: false },
            { task: 'Spec compliance check', done: false },
            { task: 'Client approval confirmation', done: false },
          ],
          depends_on: ['Revisions'],
          is_client_visible: true,
          is_ai_task: false,
        },
      ],
    },
    {
      name: 'Delivery',
      order: 5,
      weight: 0.15,
      objectives: [
        {
          title: 'Export Master',
          description: 'Export broadcast-quality master file in all required formats.',
          department: 'Post-Production',
          priority: 'High',
          estimated_hours: 2,
          offset_ratio: 0.0,
          checklist: [
            { task: 'Export ProRes/DNxHD master', done: false },
            { task: 'Export H.264/H.265 for web', done: false },
          ],
          depends_on: ['Final QA'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Client Delivery',
          description: 'Deliver all final files to client via secure portal or cloud delivery link.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 1,
          offset_ratio: 0.35,
          checklist: [
            { task: 'Upload finals to portal', done: false },
            { task: 'Send delivery notification', done: false },
            { task: 'Confirm receipt', done: false },
          ],
          depends_on: ['Export Master'],
          is_client_visible: true,
          is_ai_task: false,
        },
        {
          title: 'Archive Files',
          description: 'Organize and archive all production files for long-term storage and future reference.',
          department: 'Production',
          priority: 'Medium',
          estimated_hours: 2,
          offset_ratio: 0.6,
          checklist: [
            { task: 'Organize project folder', done: false },
            { task: 'Upload to archive storage', done: false },
          ],
          depends_on: ['Export Master'],
          is_client_visible: false,
          is_ai_task: false,
        },
        {
          title: 'Backup Storage',
          description: 'Create redundant backup copy of all deliverables and raw files.',
          department: 'Production',
          priority: 'High',
          estimated_hours: 1,
          offset_ratio: 0.8,
          checklist: [
            { task: 'Create secondary backup', done: false },
            { task: 'Verify backup integrity', done: false },
          ],
          depends_on: ['Archive Files'],
          is_client_visible: false,
          is_ai_task: false,
        },
      ],
    },
  ],
};

// ============================================================
// MASTER TEMPLATE REGISTRY
// ============================================================
export const ENTERPRISE_TEMPLATES: Record<string, EnterpriseProjectTemplate> = {
  'AI Production': AIProductionTemplate,
  'Hybrid Production': HybridProductionTemplate,
  'Normal Production': NormalProductionTemplate,
};

export const DEFAULT_TIMELINE_DAYS: Record<string, number> = {
  'AI Production': 45,
  'Hybrid Production': 35,
  'Normal Production': 25,
};
